### ISSUE TITLE
新增管理员页面

### ISSUE THREAD

**Issue by liu-jiachen** [TencentBlueKing/bk-training-open#103]
a. 可以看到组内成员谁写了日报，谁没写。
b. 可以一键通知没写日报的成员，进行补签（请假的同学不发送）。
c. 可以对组内成员的日报进行评价，通知方式：发给所有人和发给被评价者。

**Comment by ZHXDiDa** [comment]
前端+后端
评价：标星+文本
标星：https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/rate
文本：https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/input

**Comment by ZHXDiDa** [comment]
后端：ChengxingCui
