### ISSUE TITLE
优秀日报展示页面

### ISSUE THREAD

**Issue by liu-jiachen** [TencentBlueKing/bk-training-open#128]
管理员觉得哪个日报优秀 可以点击展示在优秀页面

**Comment by yanci777** [comment]
页面1：优秀日报分享
![image](https://user-images.githubusercontent.com/77596454/145174105-e127ae10-bfc5-434f-9111-7e9dc1177014.png)

接口设计：
1. daily表添加字段 isPerfect（默认为0=普通，1=优秀）（是否要记载操作的管理员？）
2. （未设置为优秀的日报）管理员点击“设为优秀“，调用setDailyPerfect(daily_id)接口，update daily表的isPerfect字段为1
3. （已设置为优秀的日报）管理员点击“取消优秀”，调用setDailyPerfect(daily_id)接口，update daily表的isPerfect字段为0


页面2：优秀日报展示
![image](https://user-images.githubusercontent.com/77596454/145174115-418663b7-660c-4e37-966f-f75ae9338fa0.png)

接口设计：
1. 展示优秀日报，调用url = getPerfectDaily？type=x?year=y&month=m&curPage=p&num=n
type：标识是按什么查询，0=查询全部，1=按年份查询，2=按月份查询
year：按年份查询时传入年份
month：按月份查询时传入月份
curPage：分页当前页
num：一页展示的日报数量
