### ISSUE TITLE
每周时间安排页面

### ISSUE THREAD

**Issue by liu-jiachen** [TencentBlueKing/bk-training-open#129]
可以在这个页面中填写每周可以参与项目的时间  目前咱们是通过表格的形式统计 这个功能放到这个页面中

**Comment by 404-error-404** [comment]
## 表设计：FreeTime

| 字段名      | 类型              | 备注                     |
| ----------- | ----------------- | ------------------------ |
| date        | datetime.date     | 日期                     |
| start_time  | datetime.time     | 当天有空时间段的起始时间 |
| end_time    | datetime.time     | 当天有空时间段的结束时间 |
| user_id     | int               | 用户id                   |
| create_time | datetime.datetime | 创建时间                 |
| update_time | datetime          | 更新时间                 |

## 接口设计：

1. 增加空闲时间

   ```
   POST /free_time/
   ```

   参数：json格式，放在request.body中

   | 参数名     | 类型 | 说明                   |
   | ---------- | ---- | ---------------------- |
   | free_times | list | 要添加的所有空闲时间段 |

   具体格式如下：

   ```json
   {
       "free_times": {
           "2021-12-7":[			# 键为该空闲时间段的日期
               "10:50-12:00",		# 以'-'连接的两个时间，起始时间和结束时间，精准到分钟
               "14:00-18:00"
           ],
           "2021-12-8":[
               "14:00-18:00"
           ]
       }
   }
   ```

   

2. 修改空闲时间

   ```
   PUT /free_time/
   ```

   参数：json格式，放在request.body中

   | 参数名         | 类型          | 说明                                        |
   | -------------- | ------------- | ------------------------------------------- |
   | free_time_id   | int           | 要修改的空闲时间id，如：1                   |
   | new_date       | datetime.date | 修改后的日期                                |
   | new_start_time | datetime.time | 修改后的起始时间，如：10:30                 |
   | new_end_time   | datetime.time | 修改后的结束时间，需大于起始时间，如：11:30 |

   

3. 删除空闲时间

   ```
   DELETE /free_time/?free_time=<空闲时间id>
   ```

   参数：放在url中

   | 参数名    | 类型 | 说明                 |
   | --------- | ---- | -------------------- |
   | free_time | int  | 要删除的空闲时间的id |

   

4. 获取自己的空闲时间

   ```
   GET /free_time/
   ```

   参数：放在url中

   | 参数名     | 类型          | 说明                     |
   | ---------- | ------------- | ------------------------ |
   | start_date | datetime.date | 要获取空闲时间的起始日期 |
   | end_date   | datetime.date | 要获取空闲时间的结束日期 |

   说明：

   end_date >= start_time，会返回包括start_date和end_date在内的所有日期的空闲时间

   返回数据示例：

   ```json
   {
       "data": {
           "2021-12-7":[			# 键为该空闲时间段的日期
               "10:50-12:00",		# 以'-'连接的两个时间，起始时间和结束时间，精准到分钟
               "14:00-18:00"
           ],
           "2021-12-8":[
               "14:00-18:00"
           ]
       },
       "total_minutes": 20
   }
   ```

   

5. 获取同组所有成员/指定成员的空闲时间

   ```
   GET /group_free_time/
   ```

   参数：放在url中

   | 参数名     | 类型          | 说明                                                         |
   | ---------- | ------------- | ------------------------------------------------------------ |
   | start_date | datetime.date | 要获取空闲时间的起始日期                                     |
   | end_date   | datetime.date | 要获取空闲时间的结束日期                                     |
   | member_if  | int           | 可选<br />有该参数则获取指定成员的空闲时间<br />无该参数则获取所有成员的空闲时间 |

   说明：

   end_date >= start_time，会返回包括start_date和end_date在内的所有日期的空闲时间

   返回数据示例：

   ```json
   {
       "data": {
           1: {	# 键为成员id
               "2021-12-7":[			# 键为该空闲时间段的日期
                   "10:50-12:00",		# 以'-'连接的两个时间，起始时间和结束时间，精准到分钟
                   "14:00-18:00"
               ],
               "2021-12-8":[
                   "14:00-18:00"
               ]
           },
           "total_minutes": 20
       },
       ...
   }
   ```

**Comment by ZHXDiDa** [comment]
## Model

user_id -> username

## Func

需要设计一个Handler来处理Model的读写，以确保时间不重叠。

返回的格式可能需要改一改

针对个人
![image](https://user-images.githubusercontent.com/41963680/144984129-39cb29af-9d46-415c-bf81-025deca82afc.png)

针对组
![image](https://user-images.githubusercontent.com/41963680/144984240-e530123e-ed8e-4d8e-9751-db7288980a99.png)

更新方法改为 PATCH

组界面暂时不考虑查看单人的空闲时间，可以精简一下参数

**Comment by ZHXDiDa** [comment]
Model 直接用 Datetime 会不会好一点？不然从数据库拿数据要比较很麻烦

**Comment by ZHXDiDa** [comment]
`PATCH /free_time/` -> `PATCH /free_time/:id/`

`DELETE /free_time/?free_time=<空闲时间id>` -> `DELETE /free_time/:id/`

`GET /group_free_time/` -> `GET /group_free_time/:group_id/`

`is_valid_time` 还要判断输入是否为同一天

`update_free_time` 的 username 感觉没必要，毕竟有id了

`delete_free_time` 同上，如果要实现只能操作自己的，可以再Handler初始化的时候传入operator用于校验

**Comment by ZHXDiDa** [comment]
目前看来这个Handler过于依赖Model了，可以考虑写成Model方法，使用自定义Manager的形式实现

```
class FreeTimeManage(models.Manager):
    def add_new_free_time(username: str, new_time_list):
        pass

class FreeTime(models.Model):
    objects = FreeTimeManage()

FreeTime.objects.add_new_free_time(xxx, xxx)
```

**Comment by ZHXDiDa** [comment]
1. `is_valid_time`  的 `ignore_free_time_id` 是拿来干啥的呢？不太理解
2. `add_new_free_time` -> `add_free_time`
3. `new_time_list` -> `free_times`
4. `update_free_time` 这个可以直接修改 Manager 的 update 方法来实现
5. `delete_free_time` 同 4
