### ISSUE TITLE
[optimize] 后端文件拆分

### ISSUE THREAD

**Issue by OrenZhang** [TencentBlueKing/bk-training-open#225]
按照 Model 归类和拆分为不同的 views.py 以及 models.py，目前单文件过长不易查找

**Comment by xingcheno** [comment]
manage 
首页
journal_template
获取用户所在组的所有的日报模板
日报模板的增删改查功能
日报模块的增删改查
日报分页器
journal_manage
获取用户已提交的所有日报日期
检查工作日日报是否已填写
修改日报的优秀状态
获取组内优秀日报
评价组员日报
提醒未写日报成员写日报
删除日报中评价（仅可以删除自己的）
修改日报的指定评论
发生邮件给所有组成员（可以发生多个邮件）
获取成员的日报信息
group
获取组信息
添加组
删除组
编辑组
用户申请入组
获取申请入组列表
管理员同意用户入组
查询用户组列表
查询组的成员列表
组内移除用户（可能不是当前用户），用户退出组
获取所有(未在、未申请)组信息
 获取组内管理员列表
获取有权限管理的所有组
查询成员是否已加入指定小组，返回未加入小组的成员姓名
user
 注册不存在的用户信息
添加用户信息
获取当前用户信息
更改用户信息
 从蓝鲸平台，拉取所有用户列表
检查用户管理
off_day
请假
撤回请假条
展示未请假人和请假人
free_time
空闲时间的增删改查
空闲时间 改删
查询空闲时间
