### ISSUE TITLE
新增请假功能

### ISSUE THREAD

**Issue by liu-jiachen** [TencentBlueKing/bk-training-open#95]

**Comment by liu-jiachen** [comment]
先写后端，前端优化完成后再完成前端

**Comment by xingcheno** [comment]
### 表设计
1. - leave_time 请假时间
2. - deadline 截止时间
3. - reason   请假理由
4. - username 用户名（防止姓名相同）
5. - create_name请假人
6. - leave_status请假状态 {0：请假中 1：假期结束}
7. - ready 备用字段
### 接口设计
1一、save_leave_person（request）
保存请假人信息到数据库
 需要前端信息：
1. leave_time 请假时间
2.deadline 截止时间
3. reason   请假理由
4.选定管理员（给管理员发一份邮件）
二、show_all_leave_person(request)
展示所有请假人信息（按时间倒叙展示）
需要信息：无
管理员可以看见自己所有的组成员，成员可以看见自己加入的所有组成员
三、select_show
0:展示全部 1：展示请假中 2：展示请假结束
都按时间倒序展示
四、方法 is_deadline()
判断数据库所有人请假时间是否到期，到期后将请假状态改为假期结束 
ci方法放入show_all_leave_person里面

**Comment by ZHXDiDa** [comment]
1. 表设计改为表格格式或者 model class 截图
2. 请假相关改为 off day, person
3. 需要前端信息 -> 输入参数
4. 不用选管理员，直接所有管理员，不然还需要管理员互相知会的话有点麻烦
5. 方法名再优化一下

**Comment by xingcheno** [comment]
表设计
![image](https://user-images.githubusercontent.com/86355346/144042480-289cea52-9355-4586-960a-5383c2492014.png)

接口设计
一、save_leave_person（request）
保存请假人信息到数据库
输入参数：
1.off_day_date 请假时间
2.deadline 截止时间
3.reason 请假理由
二、show_all_off_person(request)
展示所有请假人信息（按时间倒叙展示）
输入参数：无
管理员可以看见自己所有的组成员，成员可以看见自己加入的所有组成员
三、select_show
0:展示全部 1：展示请假中 2：展示请假结束
都按时间倒序展示
四、方法 judge_off_day_situation()
判断数据库所有人请假时间是否到期，到期后将请假状态改为假期结束
此方法放入show_all_off_person(request)里面

**Comment by ZHXDiDa** [comment]
#### 代码规范，class 以 `OffDay` 这种形式，方法以 `login_exempt` 这种形式

#### Model
- `off_day_date` -> `off_date`
- 不需要 `deadline`，跨日期创建多条即可，方便索引
- `off_by` -> `user`
- `off_name` 是否有必要呢？
- `off_status` -> `status`，存储的状态少了
- `to_json` 避免使用 `eval` 方法

#### Methods
- `save_off_person` -> `add_off_info` (POST)
    - `off_day_date` -> `date`
- `show_all_off_person` -> `list_off_info` (GET)
    - 是否需要输入日期、组信息？
- `select_show` 是什么接口
- `judge_off_day_situation` -> `check_off_status`
    - 没有假期结束这一说
    - 该接口作为公共函数，需要提供给其他地方使用，同时还需要一个 `list_at_work_user` 方法

**Comment by ZHXDiDa** [comment]
### Model
- OffDay   ->Day<-   ->D<-
- 日期和用户应该组成唯一键
- `off_date` 的格式化应该使用 `datetime` 的日期转字符串格式化，不能直接 `str`

### Methods
- `add_off_info` 输入参数是不是忘改了
- `list_off_info` -> `list_off_users`
    - 两个参数应该都是必须的
- `check_off_status` 不能从请假表中移除，没有记录了

**Comment by ZHXDiDa** [comment]
- uniq 是放在 Meta 里面的
- `remove_off_users` -> `remove_off` 
    - 不是用来提前销假的，是用于不请假了，这一块没有销假这个概念
    - 输入参数少了，日期怎么没有传入呢
- `check_off_status`
    - “到期后将从请假表中移除”，请假得留底，不能删的
